name: ptg

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit=10.2 # version for cluster compatibility
  - pip
  - python=3.8 # version for PyTorch Geometric compatibility
  - tqdm # provides progress bars to Python loops
  - jupyter
  - pytorch=1.7 # version for cluster compatibility
  - torchaudio # unnecessary for production (but useful for examples)
  - torchvision # unnecessary for production (but useful for examples)
  - networkx # required by PyTorch Geometric
  - torchmetrics # modular ML metrics for PyTorch
  - pytorch-lightning # parallelisation
  - ray-tune # tuning hyperparams
  - hyperopt # tuning hyperparams
  - tensorboard # visualising metrics
  - scipy
  - numpy
  - numba # JIT compilation and other performance boosts
  - pandas # DataFrames
  - h5py # interface to HDF5 data files
  - python-louvain
  - scikit-learn
  - requests
  - rdflib
  - googledrivedownloader # required by PyTorch Geometric
  - ase
  - jinja2
  - zenodo_get # downloading public datasets
